### ISSUE TITLE
Add log levels

### ISSUE THREAD

**Issue by rfoel** [mooyoul/serverless-latest-layer-version#34]
I thought we can implement a plugin option for controlling log output verbosity.

For example, 
- INFO: Most verbose logging output. Prints any informational log (e.g. prints entire layer replacements without deduplication, with entire context including function name and layer arn)
- WARN: Prints warnings only. Prints warnings only (e.g. prints deduplicated layer replacements - which current PR does)
- ERROR: Prints errors only. Prints errors only (e.g. unknown layer arn)

Then, Users can control log verbosity like this:

```yaml
// serverless.yml

// ... (truncated)
plugins:
  - serverless-latest-layer-version
custom:
  latestLayerVersion:
    logLevel: WARN
```

Anyway this isn't mandatory for merging. You can ignore this request ;)

_Originally posted by @mooyoul in https://github.com/mooyoul/serverless-latest-layer-version/pull/33#discussion_r1015949285_
